# build_chord_banks.py
# Run on desktop Python, NOT on CircuitPython.

import ast
from pathlib import Path
import re
import urllib.request

URL = "https://raw.githubusercontent.com/ldrolez/free-midi-chords/main/chords.py"
OUT_FILE = Path(__file__).with_name("Build") / "chords.py"
PADS_PER_BANK = 12

ROMAN_TO_DEGREE = {
    "I": 0, "II": 1, "III": 2, "IV": 3, "V": 4, "VI": 5, "VII": 6,
}

SHAPES = {
    "": (0, 4, 7),
    "M": (0, 4, 7),
    "m": (0, 3, 7),
    "dim": (0, 3, 6),
    "5": (0, 7),

    "M-5": (0, 4, 6),
    "sus2": (0, 2, 7),
    "sus4": (0, 5, 7),
    "6": (0, 4, 7, 9),
    "M6": (0, 4, 7, 9),
    "7": (0, 4, 7, 10),
    "dom7": (0, 4, 7, 10),
    "7-5": (0, 4, 6, 10),
    "7+5": (0, 4, 8, 10),
    "7sus4": (0, 5, 7, 10),
    "maj7": (0, 4, 7, 11),
    "M7": (0, 4, 7, 11),
    "M7+5": (0, 4, 8, 11),
    "add4": (0, 4, 5, 7),
    "add9": (0, 4, 7, 14),
    "sus4add9": (0, 5, 7, 14),
    "2": (0, 4, 7, 14),
    "add11": (0, 4, 7, 17),
    "69": (0, 4, 7, 9, 14),
    "9": (0, 4, 7, 10, 14),
    "maj9": (0, 4, 7, 11, 14),
    "9sus4": (0, 5, 7, 10, 14),
    "7-9": (0, 4, 7, 10, 13),
    "7+11": (0, 4, 7, 10, 18),

    "m6": (0, 3, 7, 9),
    "m7": (0, 3, 7, 10),
    "m7-5": (0, 3, 6, 10),
    "m7+5": (0, 3, 8, 10),
    "dim6": (0, 3, 6, 9),
    "dim7": (0, 3, 6, 9),
    "mM7": (0, 3, 7, 11),
    "madd4": (0, 3, 5, 7),
    "madd9": (0, 3, 7, 14),
    "m69": (0, 3, 7, 9, 14),
    "m9": (0, 3, 7, 10, 14),
    "m7b9b5": (0, 3, 6, 10, 13),
    "m7add11": (0, 3, 7, 10, 17),
    "mM7add11": (0, 3, 7, 11, 17),
}


def load_repo_lists():
    src = urllib.request.urlopen(URL).read().decode("utf-8")
    tree = ast.parse(src)

    result = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            name = node.targets[0].id if isinstance(node.targets[0], ast.Name) else None
            if name in ("prog_maj", "prog_min", "prog_modal"):
                result[name] = ast.literal_eval(node.value)

    return result


def parse_symbol(sym):
    accidental = 0

    if sym.startswith("b"):
        accidental = -1
        sym = sym[1:]
    elif sym.startswith("#"):
        accidental = 1
        sym = sym[1:]

    m = re.match(r"([ivIV]+)(.*)$", sym)
    if not m:
        raise ValueError("Could not parse chord symbol: " + sym)

    roman_raw, suffix = m.groups()
    degree = ROMAN_TO_DEGREE[roman_raw.upper()]

    if roman_raw.islower() and suffix == "":
        suffix = "m"

    if roman_raw.islower() and suffix in ("6", "7", "9", "69"):
        suffix = "m" + suffix

    if suffix not in SHAPES:
        raise ValueError(f"Unknown suffix {suffix!r} from symbol {sym!r}")

    return degree, accidental, SHAPES[suffix]


def line_to_chords(line):
    left = line.split("=", 1)[0].strip()
    symbols = left.split()

    out = []
    seen = set()

    for sym in symbols:
        chord = parse_symbol(sym)

        if chord not in seen:
            seen.add(chord)
            out.append(chord)

    return out


def rotate_shape(shape, inversion):
    notes = list(shape)

    for _ in range(inversion):
        notes.append(notes.pop(0) + 12)

    return tuple(notes)


def make_12_pad_bank(chords):
    pads = []
    inv = 0

    while len(pads) < PADS_PER_BANK:
        for degree, accidental, shape in chords:
            if len(pads) >= PADS_PER_BANK:
                break

            inv_shape = rotate_shape(shape, inv)
            pads.append((degree, accidental, inv_shape))

        inv += 1

    return tuple(pads)


def intern_bank(bank, chord_ids, chord_table):
    encoded = []

    for chord in bank:
        if chord not in chord_ids:
            chord_ids[chord] = len(chord_table)
            chord_table.append(chord)

        cid = chord_ids[chord]
        if cid > 255:
            raise RuntimeError("Too many unique pad chords for 1-byte IDs.")

        encoded.append(cid)

    return bytes(encoded)


def convert_all(lists):
    chord_ids = {}
    chord_table = []

    banks = []
    bank_seen = set()
    ranges = {}

    for list_name in ("prog_maj", "prog_min", "prog_modal"):
        start = len(banks)

        for line in lists[list_name]:
            chords = line_to_chords(line)
            bank = make_12_pad_bank(chords)

            if bank in bank_seen:
                continue

            bank_seen.add(bank)
            banks.append(intern_bank(bank, chord_ids, chord_table))

        end = len(banks)
        ranges[list_name] = (start, end)

    return chord_table, banks, ranges


def emit_tuple_bytes(name, values):
    lines = [f"{name} = ("]
    for b in values:
        lines.append(f"    {repr(b)},")
    lines.append(")")
    return "\n".join(lines)


def emit_output(chord_table, banks, ranges):
    lines = []
    lines.append("# Auto-generated by build_chord_banks.py")
    lines.append("# Copy this file to CircuitPython.")
    lines.append("")
    lines.append("PADS_PER_BANK = 12")
    lines.append("")
    lines.append("# Mode IDs")
    lines.append("MODE_MAJOR = 0")
    lines.append("MODE_MINOR = 1")
    lines.append("MODE_DORIAN = 2")
    lines.append("MODE_PHRYGIAN = 3")
    lines.append("MODE_LYDIAN = 4")
    lines.append("MODE_MIXOLYDIAN = 5")
    lines.append("MODE_LOCRIAN = 6")
    lines.append("")
    lines.append("# Optional UI labels. Delete if you need maximum RAM savings.")
    lines.append("MODE_NAMES = ('Maj', 'Min', 'Dor', 'Phr', 'Lyd', 'Mix', 'Loc')")
    lines.append("")
    lines.append("# Roman degree offsets relative to key root.")
    lines.append("# Accidentals in chord symbols handle bIII, #IV, bVII, etc.")
    lines.append("DEGREE_OFFSETS = b'\\x00\\x02\\x04\\x05\\x07\\x09\\x0b'")
    lines.append("")

    lines.append("# Each chord: degree, accidental, interval-bytes")
    lines.append("# degree: 0=I, 1=II, 2=III, 3=IV, 4=V, 5=VI, 6=VII")
    lines.append("# accidental: -1=flat, 0=natural, 1=sharp")
    lines.append("CHORDS = (")
    for degree, accidental, shape in chord_table:
        lines.append(f"    ({degree}, {accidental}, {repr(bytes(shape))}),")
    lines.append(")")
    lines.append("")

    lines.append(emit_tuple_bytes("BANKS", banks))
    lines.append("")

    maj_a, maj_b = ranges["prog_maj"]
    min_a, min_b = ranges["prog_min"]
    mod_a, mod_b = ranges["prog_modal"]

    lines.append(f"MAJOR_RANGE = ({maj_a}, {maj_b})")
    lines.append(f"MINOR_RANGE = ({min_a}, {min_b})")
    lines.append(f"MODAL_RANGE = ({mod_a}, {mod_b})")
    lines.append("")
    lines.append("# Which progression list each UX mode uses.")
    lines.append("# Major uses prog_maj, minor uses prog_min, all other modes use prog_modal.")
    lines.append("MODE_RANGES = (")
    lines.append("    MAJOR_RANGE,")
    lines.append("    MINOR_RANGE,")
    lines.append("    MODAL_RANGE,")
    lines.append("    MODAL_RANGE,")
    lines.append("    MODAL_RANGE,")
    lines.append("    MODAL_RANGE,")
    lines.append("    MODAL_RANGE,")
    lines.append(")")
    lines.append("")

    lines.append("""
def mode_count():
    return len(MODE_RANGES)


def mode_name(mode):
    return MODE_NAMES[mode]


def bank_count(bank_range=None):
    if bank_range is None:
        return len(BANKS)
    return bank_range[1] - bank_range[0]


def bank_count_for_mode(mode):
    return bank_count(MODE_RANGES[mode])


def get_bank(index, bank_range=None):
    if bank_range is not None:
        index = bank_range[0] + index
    return BANKS[index]


def get_bank_for_mode(mode, index):
    return get_bank(index, MODE_RANGES[mode])


def chord_notes_from_id(chord_id, key_root=0, octave=4):
    degree, accidental, intervals = CHORDS[chord_id]
    root = octave * 12 + key_root + DEGREE_OFFSETS[degree] + accidental
    return tuple(root + i for i in intervals)


def pad_notes(bank, pad_index, key_root=0, octave=4):
    chord_id = bank[pad_index]
    return chord_notes_from_id(chord_id, key_root, octave)


def bank_pad_notes(bank_index, pad_index, key_root=0, octave=4, bank_range=None):
    bank = get_bank(bank_index, bank_range)
    return pad_notes(bank, pad_index, key_root, octave)


def mode_bank_pad_notes(mode, bank_index, pad_index, key_root=0, octave=4):
    bank = get_bank_for_mode(mode, bank_index)
    return pad_notes(bank, pad_index, key_root, octave)
""".strip())

    return "\n".join(lines) + "\n"


def main():
    lists = load_repo_lists()
    chord_table, banks, ranges = convert_all(lists)

    output = emit_output(chord_table, banks, ranges)

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUT_FILE.open("w", encoding="utf-8") as f:
        f.write(output)

    print("Generated:", OUT_FILE)
    print("Unique pad chords:", len(chord_table))
    print("Unique 12-pad banks:", len(banks))
    print("Major banks:", ranges["prog_maj"])
    print("Minor banks:", ranges["prog_min"])
    print("Modal banks:", ranges["prog_modal"])


if __name__ == "__main__":
    main()